### ISSUE TITLE
2 Hops for Vesting Tokens before 1 year hold/Rule 144 compliance

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#121]
Right now we're originating a block of vesting tokens from a singular address, the tokens move once and then any subsequent sends are invalid for N blocks where N ~= 1 year of real-time. The problem here is security: if I must re-use the same private key to make Reg S/OTC transactions, could be tricky. Can't be too paranoid when it comes to this stuff.

Therefore, I'd like to do the initial vesting token distribution in one shot, distributing all the tokens, and reserve some addresses in chunks for future deals. Therefore, we must adjust the freeze mechanism to only disable sends for one year after the second send.

Also, after the 1 year, tokens should become free to be sent liberally. The sellers would need to trade with non-US persons to keep in compliance with Rule 144 but otherwise the rule says the assets can float freely.

Should be a small modification in the logic to permit 2 sends before the 1 year hold period.

**Comment by patrickdugan** [comment]
Insert if/then logic regarding the last time a sendVestingTokens tx with the given address as a destination was sent. If < 1 year worth of blocks (52560 for Bitcoin, 210240 for Litecoin) has elapsed since the tx, then it's valid, otherwise the send is invalid. *Unless* (this is what effectively implements this ticket) the sender of that send tx was the privelidged origination address.

The idea being, we can distribute VTs from the origin key and empty that address, then send again, then those recipients are bound by SEC rule 144a for a year.

**Comment by santos177** [comment]
working on hops branch

**Comment by patrickdugan** [comment]
This is in the general testing of the Vesting Tokens so since the code is done I'll close this ticket.
