### ISSUE TITLE
Total TOTAL/ALL supply RPC

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#124]
Each block, there is a finite and deterministic total quantity of TOTAL/ALL existing in the layer, after Node Reward tx and order prints add in new supply. Ideally, this RPC should take block height as a parameter and we could chart supply over time down to the block, but at the very least being able to track a headline number is useful. If it's a huge time-sink to try and provide per-block tracking we could defer to a parallel service to ping a node and track the numbers.

**Comment by santos177** [comment]
Working on it , using branch suppy
