### ISSUE TITLE
Get dCurrency Totals

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#125]
Get total outstanding supply of dUSDs and other dCurrency, taking as a parameter their property IDs or the text codename for the currency (e.g. "dUSD" as a string). Returns outstanding supply. It would be a non-consensus changing extra-credit if this RPC - at a later date - supported-block block historical indexing of these values, but, as with the other RPC that can be logged in parallel for now.

**Comment by santos177** [comment]
Working on it, see dcurrency branch.
