### ISSUE TITLE
Adjust Channel Expiration

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#132]
Currently Trade Channels expire and are deleted from the registry/trades cease to be valid after ~24 hours worth of blocks. This is problematic because it requires wasted fees and time re-establishing trade channels. Instead, a TC should have an expiry of creation time + 144 blocks (BTC) or 580 blocks (LTC) where all unpublished trades become invalid, but every time a trade is printed (e.g.  published to be confirmed into the blockchain and create a fee event) this timer resets to 144 blocks after this event. 

Additionally the object data about channels should include this block height where it would expire and include the data in the RPC related to Trade Channels.

**Comment by santos177** [comment]
Implemente yet inside tradelayer on litecoin.
