### ISSUE TITLE
Fee Caching

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#151]
The fee behavior is supposed to take a portion of it and buy ALL or TOTAL on the mDex with the collateral currency in question (or with the taker part of the mDex trade) but the default state of any mDex pair is an empty orderbook. Therefore we need an ante-chamber to an insurance fund, a fee cache, for each property that accumualtes until such time as there is an order on the mDex orderbook for that propertyid. Then if the order(s) is/are not big enough, pro-rate the portion of the fee cache to clear all available orders until the cache is empty.

**Comment by santos177** [comment]
working on fee-caching branch
