### ISSUE TITLE
Vesting Token Checking Trade Channel Volume

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#152]
Lihki's original implementation didn't account for the new Trade Channel type tx's so let's add support for the 3 kinds of TC trades.

**Comment by santos177** [comment]
LTC volume is yet added in the channels.

**Comment by patrickdugan** [comment]
Please add volume for on-chain contractDex trades and trade channel contractDex trades as well. We will skip token-to-token since that is less important to the overall ecosystem, especially early on, and save some time.

The formula for contractDex volume is: trade amount * contract notional * the LTC price of the collateral currency. So you'd look at that collateral currency id parameter in the contract object, then look up the LTC dex data on it, and if there are no trades that block then look at the last trade that occured. If no trades have occured then don't include the volume. (This could be a junk coin with fake wash-trading fees paid in the junk coin, for instance).

**Comment by santos177** [comment]
working on volume branch
