### ISSUE TITLE
Theory on margins issue

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#177]
haven't checked too deep, but since i can't buy or sell contracts yet, i think that instead of the math being the problem it might be the collateral choosing. Before when we were testing stuff for demos, everything was collateralized in ALL or sLTC (being innate propertyid 1 and 3 if i remember correctly) while Pid 1 and 2 were ecosystems, so it might be that some of that code is still there and when i create contracts collateralized in propertyid 16, it can't use those tokens, so it always spits the same error that we don't have enough balance for margin.

**Comment by santos177** [comment]
working on collateral branch.
