### ISSUE TITLE
Lower Priority Payload RPCs

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#184]
Since the administrators of Oracles, KYC registrars and Managed Property addresses will generally use multisig, it's important that they be able to have automated RPC calls to layer in .js or other scripts for creating multisig transactions with payloads for:

Change admin address on Oracle
Create Oracle
Publish Oracle Data
Close Out Oracle
Change admin on Managed Property (this already exists but must be updated with KYC parameter)
Create Managed Property (already exists but needs KYC parameter)
Create KYC registrar
Change admin on KYC registrar
Issue KYC attestation

**Comment by santos177** [comment]
working on payloads branch
