### ISSUE TITLE
Default Price for Volume Conversion = 0.0001, != 0

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#194]
Instead of dividing by 0 and creating a crash bug, if there's no volume for property 0 (BTC or LTC) against property xyz to figure the volume, assume that the property is worth 0.0001 of the property instead of 0.

**Comment by santos177** [comment]
@Galuf1  where is located this bug? exactly?

**Comment by Galuf1** [comment]
Trying to find the place, but should be in the Vesting functions when you add all the LTC volume. One does a triangulation from token/LTC, and that price can be 0 causing the crash.

**Comment by santos177** [comment]
working on default-price branch
