### ISSUE TITLE
 Fee Check

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#195]
Trade Channel Fees for Oracles:

1 each side

1 goes to the Oracle operator.

0.5 goes to the Oracle contract insurance cache.

0.5 goes to the Native fee cache to await buying some Property 1 and storing that in the native contract insurance cache (either ALL/LTC perpetual swap or TOTAL/BTC perpetual swap).

**Comment by Galuf1** [comment]
@santos177 Fees are not getting discounted when doing a trade, taker here takes just the margin out 
![image](https://user-images.githubusercontent.com/31936063/76107402-52bd1a00-5fb7-11ea-95a2-53fb3930c6fb.png)

and of course that means that the issuer is not getting any fees, 
![image](https://user-images.githubusercontent.com/31936063/76107430-64062680-5fb7-11ea-8aa2-6f98629561cc.png)

**Comment by santos177** [comment]
working on fee-check branch
