### ISSUE TITLE
Ecosystem Consolidation

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#196]
Since the beginning of "time" the property ids have been reserved property 1 is the metacoin and property 2 is the test version of that coin. But then in test ecosystem property 3 and beyond diverge. Since we're trying to reserve early property ids for native contracts/properties, we should just remove all the references to ecosystem to prevent it causing bugs such as an issue with cancels.

All RPC references to ecosystem parameters must be removed.

All instances in the code where ecosystem is used to delineate logic must be removed.

**Comment by santos177** [comment]
working on ecosystem branch
