### ISSUE TITLE
remove allPrice and fix tl_getmax_peggedcurrency

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#202]
the logic to get the max pegged currency, or to check how much short contracts you need vs the collatera should be revisited. In tl_getmax_peggedcurrency to calculate the max pegged currency that we use in the wallet it adds a hardcoded All price in dollars, which we used for a demo and now it doesn't make sense.

**Comment by patrickdugan** [comment]
Please mark these tickets under the Testnet Native Release Milestone, if
it's not essential to functioning margin/settlement/fees/insurance/Oracle
operations, it's not going in this month's release.

**Comment by Galuf1** [comment]
done
