### ISSUE TITLE
Remove Ecosystem Parameter from RPCPayload.cpp

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#233]
The ecosystem parameter still shows up in a lot of payload RPCs. If you haven't already, please also remove these from the primary RPC functions and of course, the tx parsing.

**Comment by santos177** [comment]
Closing this ticket. I read the code and every ecosystem reference was deleted. Please try to work in some new branch pulled from development. Master branch is not updated yet.

**Comment by patrickdugan** [comment]
Ah ok, sorry about that!
