### ISSUE TITLE
Open interest RPC

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#238]
We need to build an open interest RPC, logic has to be derived from settlement tracking of contracts, where we can count how many new contracts are open with a buyer and a seller, and when we are closing contracts (closing at both sides), adding that amount should set a live amount of contracts.

**Comment by patrickdugan** [comment]
Aren't we already tracking net contract positions on any given block in the tallmap? It seems like this is similar to RPCs that get total # of tokens and that take the absolute value of the positives or negatives.

**Comment by Galuf1** [comment]
I don't know how you feel about it but there is 2 choices, taking absolute values or all positions, which would require iterating through the database every block to check how many positions have the key of the contract name, updated with how many they closed. Or counting what's in the containers from the contract, which rebuild from settlement to settlement. The latter one is being done, we need to put it in a RPC only, it shouldn't take much time.

The # of tokens if i'm not mistaken is not the same for contracts, we don't keep a record of new tokens since in the case of contracts every new token requires 1 token on each side.

**Comment by patrickdugan** [comment]
Good point, ideally we could track OI between blocks but OI between
settlements is acceptable if it's easier.

**Comment by Galuf1** [comment]
We should be able to track it live after every block following the containers, i'll get the variable, i think i found it last time.
