### ISSUE TITLE
rounding in dex and metadex

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#258]
we have to revisit the rounding in dex and metadex, check what the logic is, unit test if it's consistent and check what's the precision we need. Also check for overflows in those unit tests, anything that involves divisions.

**Comment by santos177** [comment]
Closing this ticket after DEx and MetaDEx testing. For now math seems ok using uint256 arithmetic (in multiplication and divisions) and a clean treatment using integers. This ticket could be reopen if we find inconsistency using doubles in different machines/ OS. Travis CI can help with that.
