### ISSUE TITLE
bad rational: zero denominator when trading and calling settlement

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#272]
i guess it has to do with the block recognition, but i'm not sure, it doesn't allow the test to finish.

It's printed in the console, not in the log.

![image](https://user-images.githubusercontent.com/31936063/82264727-7a275000-9933-11ea-849b-3989307ec7ac.png)

**Comment by santos177** [comment]
This will be resolved in the next PR from settlement_work to develpment branch. The division by zero protection is written.
