### ISSUE TITLE
globalPNLALL_DUSD not populating

### ISSUE THREAD

**Issue by Galuf1** [BlockPo/BlockPo-to-Tradelayer#273]
decision is made when comparing globalPNLALL_DUSD to volumetocompare. The variable is not populating since we need that variable to track other contracts

![image](https://user-images.githubusercontent.com/31936063/82264878-bf4b8200-9933-11ea-86e1-daf6e41124f5.png)

**Comment by patrickdugan** [comment]
It seems like this has been dealt with in the process of generalizing settlement? Probably could close.

**Comment by patrickdugan** [comment]
This has been refactored but the general issue (in a different framework) should have been solved by Ale's May '22 work.
