### ISSUE TITLE
Formalization for variable limits

### ISSUE THREAD

**Issue by santos177** [BlockPo/BlockPo-to-Tradelayer#283]
Motivation:  Time ago we've been talking about write some clear spec related with limits in variables of a given contract. For example, we know the max price for bitcoin asset in bitmex is 1000 000 , and the max amount of contracts in a single order is 10 000 000. I 've been looking our code, and i saw that our margin requirement is an uint32_t variable, too small considering the fact that in a divisible variable the number 1 is equal to 100 000 000  (in our system).  

In order to have some standard , we should have a table with the limits for each important variable.

Let's talk about it here

**Comment by patrickdugan** [comment]
BitMex actually changed theirs to 100,000,000, with 0.00 as the decimals. Perhaps the limit of 64-bit integers is acceptable?
