### ISSUE TITLE
getContractVolume RPC

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#293]
An RPC that takes contractid, start block and end block and returns notional volume in a given contract.

**Comment by patrickdugan** [comment]
Did this end up getting attended to when we re-worked volume RPCs earlier? Basically I pass a propertyid that happens to be for a contract, I should see the raw # of contracts traded? If so we can close this.

**Comment by sinetek** [comment]
is this equal to tl_getmdexvolume ?

**Comment by patrickdugan** [comment]
That's my question, maybe Ale can answer it or you could test this call when we have the contracts build working and we can resolve this.

**Comment by patrickdugan** [comment]
@santos177 Do we have an RPC for contract volume?

**Comment by patrickdugan** [comment]
I am just going to implement a simple looper in .js that takes the rpc payload from the tradehistoryunfiltered RPC and loops through, picks the tx with the block, takes the contracts traded in both denominations add them up between blocks. No need for C++.
