### ISSUE TITLE
Return parameters "contractName" to "contractid"

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#295]
It seems very tricky to have to keep a list of strings, which can be duplicates, in order to refer to contracts, when one can pull listOracles and listNatives and get the propertyids of all contracts, ids which cannot be duplicates.

**Comment by Galuf1** [comment]
They cannot be duplicates. Also there is a couple reasons why you'd want the contract names, first it's already established in naming conventions how to name a contract, if we have duplicate names and search for propertyid at some point we'll have hundreds of the same contract, having to do a lot of extra code in bots to guess what's the correct contract. Also there is the problem with synchrony, if you do that you'll have to do asynchronous calls to get the identifier before do trades in a bot or using the api. With name conventions you know for sure what are you looking for, if you want the july native 2020 monthy BTC/USD you know that it's going to be called  before without pinging the code. 

Still your call, but i think that it's more clear this way and the naming convention is already established and it works.

**Comment by patrickdugan** [comment]
Can it be both? If type==string then contractName, if type==double then id?
Make them flexible that way.

**Comment by Galuf1** [comment]
i don't know if we can, can we do this @santos177 ?
