### ISSUE TITLE
Change tl_createrawtx_reference params

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#304]
In addition to the txstring and the reference address to be painted, add a 3rd optional parameter t the createrawtx_reference RPC where a 0 or null value defaults to the dust threshold (the current behavior) and a value greater than the dust value is used as the purchase proceeds to be sent to the reference tx.

We need to have this in order to write an alt. buildRaw function that then summarily uses this RPC to add another input and make everything sum out:
https://bitcoincore.org/en/doc/0.16.0/rpc/rawtransactions/fundrawtransaction/

**Comment by santos177** [comment]
I was checking the tl_createrawtx_reference, and i saw the feature you are asking : https://github.com/BlockPo/BlockPo-to-Tradelayer/blob/development/src/tradelayer/rpcrawtx.cpp#L208. Did you test the rpc using 3 arguments ?
