### ISSUE TITLE
Change getProperty and listProperties RPC to be have verbose mode

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#305]
With high verbosity these calls should return all the relevant information to be used in the Block Explorer site:

24 Hour LTC volume
24 Hour Token or Contract volume
Total token supply or contract open interest
Last traded Price
Contract Insurance Fund Balance (if applicable)

With listProperties on verbose the explorer can update based on a single RPC pingback.

**Comment by santos177** [comment]
working on branch listproperties

**Comment by santos177** [comment]
adding more info on branch listproperties_updated

**Comment by santos177** [comment]
We can re-open this ticket if we need more info on this rpc.
