### ISSUE TITLE
Pending Transactions

### ISSUE THREAD

**Issue by santos177** [BlockPo/BlockPo-to-Tradelayer#335]
We need to implement pending transactions, in order to have more details on txs status.

**Comment by patrickdugan** [comment]
This is really important for detecting unconfirmed commits and withdrawals. The mempool native to Bitcoin/Litecoin already has access, so we just need to write an RPC route to pick up on channel-related tx that are in the mempool?

**Comment by patrickdugan** [comment]
tl_listpendingtransactions

We may be able to close this as this is an extant functionality?

**Comment by patrickdugan** [comment]
Seems like a valid concern already addressed by basic mempool RPC.
