### ISSUE TITLE
KYC Valid vs. Logic Valid

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#343]
One confusing thing about our current default tx info is that you can have enough balance to do a send or trade, but it can be invalid due to KYC, and there is no error message or hint of this. 

Therefore I propose we change the isValid field in the JSON returned by the tx info RPC, to be called logicValid: <true/false> and then add an additional field, KYCValid: <true/false> in regards specifically to the validity criteria of KYC attestations.

**Comment by santos177** [comment]
I wrote a minimalist code: same isValid field and a new field: "invalidation reason". That should be enough information in order to see what happened with some particular transaction.

**Comment by patrickdugan** [comment]
That's more elegant!
