### ISSUE TITLE
Identifying Native Contracts, Native Coins, Oracle Contracts and Issued Tokens as Categories

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#346]
In addition to the elaborate ticket for the Oracle release regarding how futures contracts' property id's work, here's a reallly simple thing that will make the listproperties call return much more parse-able data without having to pass every single id through the getContractInfo call: have Category default to one of the 4 types: Native Contracts, Native Coins, Oracle Contracts and Issued Tokens. That would mean disabling the Category parameter for issueFixed and issueManaged since we'll have these canonical categories. There are different tx types relating to these tokens and there are very few native coins, just ALL, Vesting Tokens, sLTC, USDL, EURL, JPYL, CNYL. There are somewhat more native contracts. Oracles and tokens have well defined tx associated with their creation. Therefore labeling these by category in list properties makes sense.

**Comment by patrickdugan** [comment]
We could cut this if it's too much trouble, but it seems like the easiest thing is to just "hardcode" these strings into the Category part of the first few dozen property ids and assign Oracle Contracts and Issued Tokens as the default category for issued things.

**Comment by patrickdugan** [comment]
Maybe it's even too late to do that since we already published a property list? I'm ok with cutting.

**Comment by santos177** [comment]
for now we have properties and contracts separated. You can have now propertyId=1 and also contractId=1. We are listing contract in a different level db struct. Working on it using futures-01 branch.
