### ISSUE TITLE
Extending the Default Property Ids

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#347]
We previously defined a set of about 20+ core contracts relating to the native tokens and various maturies on LTC/USD and ALL/LTC. I'd like for us to prepare a cool feature we can now afford to add for the Native release, when it comes, by demarcating property id's for the following:

Native Difficulty Futures (2 week expiration period, pair of these)

Native Fee Futures (Settles on Avg. fee over 1 week, pair of these)

Native ALL/LTC Interest Rate Swap (Quarterly, pair)

Native LTC/USD Interest Rate Swap (Quarterly, pair) 

ALL/LTC Graph Default Swap (Perpetual)

LTC/USD Graph Default Swap (Perpetual)

Note: the below is color for what we have planned here and not an instruction of this ticket.

The Interest Swaps will map to the expirations of native quarterly futures and pass through the swap rate of being short the associated perpetual swaps, and cost to margin what it costs to buy futures and sell swaps.

The graph default swaps will be kind of like if I went short a USDT/USD perpetual swap and paid for holding the position. But the thing is, we don't have a USD price to compare the price of sBTC or USDL. Right? So what can we do. We have to look at the actual native insolvency value of the contract. If I'm long a GDS, I will pay an amount of money per year based on the price of the GDS (e.g. it's trading at 5%) and I'll be exposed to both sell the contract higher and take a profit, or, hold it, and get paid every time the ALL/LTC contract or the LTC/USD native swaps suffer an event where the insurance fund can't cover insolvency and there is an n% bail-in of all profits in the contract. Whoever shorts GDS agress to pay that % on the notional value of the GDS to the long, if and when such an event happens. Maybe there's a 2.5% default and the GDS seller has been 3x leveraged making 15% p.a. and then loses 7.5%, and it's not so bad, and the GDS buyer is happy to have insurance even if they over paid. This is how pension funds could actually use TradeLayer, they could hold USDL and buy the two GDS contracts, greatly reducing their overall yield. (Since native LTC/USD swap is margined by sLTC, the total return of USDL would be the combination of the ALL/LTC swap rate + the LTC/USD swap rate).

**Comment by santos177** [comment]
working on ids_update  branch
