### ISSUE TITLE
tl_getwalletbalances

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#353]
Right now, in order to make sense of what your wallet contains in terms of tl token balances and contract positions, one must use legacy Bitcoin RPCs to see the addresses that have dusts, or another to include addresses that are fully spent (but which may host tl balances/positions) and then loop through and look at those. The C++ client ought to be able to loop through and make sense of that in a single RPC, returning a JSON of each address and the underlying contract and token values for those. To make this super-usable, the JSON should also include any LTC values that would have been seen in listunspent.

**Comment by sinetek** [comment]
https://github.com/BlockPo/BlockPo-to-Tradelayer/pull/459
