### ISSUE TITLE
LTC Trade Fees

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#369]
If on the open Dex, it's slow, it's uncertain, you're short the inherent optionality of matching on Bitcoin or Litecoin when you try to arb one of those, so let's leave that at 0. It's the ground-state for everything.

But for Trade Channels, the receiver of the tokens should be deducted a 0.5 bps fee.

**Comment by santos177** [comment]
working on branch fees
