### ISSUE TITLE
Trade History RPCs removed token to token or token to LTC history

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#384]
We should grab the legacy code for those calls really quick or do edits on our parts to make the tl_gettradehistory and tl_gettradehistoryunfiltered calls either:

1) polymorphize their parameters, accepts two property ids, if the second id is null then it's presumably a contract's history that is being requested.

2) Make a separate set of RPCs relating to tokens.

**Comment by santos177** [comment]
we can re-open this ticket if we need more rpcs or data related.
