### ISSUE TITLE
Floating point exception in CallingSettlement().

### ISSUE THREAD

**Issue by sinetek** [BlockPo/BlockPo-to-Tradelayer#390]
Sometimes when starting the application I get an exception and things crash.

```
$ ./src/qt/litecoin-qt 
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Floating point exception
```

This happens in `bool CallingSettlement()`, as you can see, we have a division by zero:

```C++
bool CallingSettlement()
{
    extern int BlockS;

    int nBlockNow = GetHeight();

    /***********************************************************************/
    /** Calling The Settlement Algorithm **/

    if (   ------>>>>>>>   nBlockNow%BlockS   <<<<<<<<------   == 0 && nBlockNow != 0 && path_elef.size() != 0 && lastBlockg != nBlockNow)
    {

        PrintToLog("\nSETTLEMENT : every 8 hours here. nBlockNow = %d\n", nBlockNow);
        pt_ndatabase = new MatrixTLS(path_elef.size(), n_cols); MatrixTLS &ndatabase = *pt_ndatabase;
        MatrixTLS M_file(path_elef.size(), n_cols);
        fillingMatrix(M_file, ndatabase, path_elef);
        n_rows = size(M_file, 0);
        PrintToLog("Matrix for Settlement: dim = (%d, %d)\n\n", n_rows, n_cols);

        /*****************************************************************************/
```

How should this case be handled??
Can you clean up this function, it's pretty horrible. What is a BlockS?
I'm not sure if this is right:

```C++
    if (BlockS && nBlockNow%BlockS == 0 && nBlockNow != 0 && path_elef.size() != 0 && lastBlockg != nBlockNow)
```

**Comment by santos177** [comment]
@sinetek : 1) the qt is not working for now. We are just working with litecoind, and litecoin-cli. 2) BlockS is the "frecuency" of the perpetual settlement (for now his value is 500, you can see it in the file called initial_conditions.h located in src folder), i don't know why you have issues with that variable. 3) You can make PR and tests using development branch (master is not the last update)

**Comment by santos177** [comment]
Closing this one, we don't have qt supported for now. @sinetek  feel free to reopen it in the future.
