### ISSUE TITLE
Channel Trades getting Invalidated for KYC reasons even when KYC is set

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#428]
Running these scripts:

https://github.com/patrickdugan/tradelayer_wallet_mono_repo_v1/blob/master/api/bot/bot_receiver.js

https://github.com/patrickdugan/tradelayer_wallet_mono_repo_v1/blob/master/api/bot/bot_listener.js

We generated a number of trades and fitted all addresses with self-attestation, KYC 0, to trade tokens which are KYC 0. Nonetheless several trades were invalidated for KYC reasons. We need to double check that with testnet functional tests.

**Comment by santos177** [comment]
Closing for now, it isn't a core issue. It can be re-opened if there's some changes we need to write.
