### ISSUE TITLE
Create Payload: Transfer

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#81]
Params: propertyid, amount, reference vOut for destination address

Instead of having to get a tx committed to Bitcoin or Litecoin every time you open a channel, and every time you close it, what if you could instantly transfer capital already commited between channels with a single co-sign?

If a single user commits capital not to a multisig they made with another trader, but to their own single sig address, they could sign these Tranfer tx's single sig and another trader could accept that "cheque" as collateral to start trading in a new trade channel. It's like Lightning's Channel Factories, but simpler. 

Due to the anycast nature of the TradeLayer environment, complementing the base layer's broadcast nature and Lightning's unicast nature, there is no need to path capital between a network of channels and route it, it's always possible to move money from channel A to channel Z in one hop, just as easily as you can move it to any other channel. 

The risk of transfer is hot keys used for multisigs can be used to try and steal funds if compromised, so keep your keys safe. But the advantage that this risk gives, is it increases the potential throughput of trading volumes to near-infinity, as co-operative users can always roll transfers for each other to fund any trading relationship on the internet in a few milliseconds. In theory, there'd be no need to settle ever, because you can just move, trade, settle PNL, move, trade, ect. - however in practice people will generally find a settlement frequency that is economic to their risk-tolerance and patience. Indefinite usage of signed but unpublished transactions would require watchtower services to enforce the option to publish, when users are offline.

**Comment by santos177** [comment]
Almost complete with PR #90
