### ISSUE TITLE
Re-Do Dex Lvl. 1 Transaction as OP_Return

### ISSUE THREAD

**Issue by patrickdugan** [BlockPo/BlockPo-to-Tradelayer#83]
The original Dex model was based on multisig in the old, weird sense, not the cool, modern, Lightning Network-esque sense, and included the Exodus address as a reference output in each transaction. These BTC dusts actually added up over the years to a couple of BTC. It was made to pin that tranasction to being a part of this system, where all the Mastercoins originated from Exodus, and move by reference to it. But then Class C and D transactions using OP_Return game to proliferate in the 2016 and later version of Omni.

Now we must re-do Dex Lvl. 1 to avoid any reference to an exodus address. Make Offer, Accept Offer and Deliver_LTC will become their own tx types as OP_Return, with the existing RPCs for them being adjusted to the new model. Make Offer should be modified so that a reference address can allow the token seller to tag a multisig trade channel for use in atomically closing a trade for LTC, but if Make Offer doesn't have a reference address then it is assumed to be an open offer on the global orderbook.

**Comment by santos177** [comment]
Working on this issue on dex branch

**Comment by patrickdugan** [comment]
Good, this is something we really ought to have!
