### ISSUE TITLE
Consider blockchain checkpoints

### ISSUE THREAD

**Issue by santos177** [BlockPo/BlockPo-to-Tradelayer#98]
In omnicore (bitcoin) also on wormhole (bitcoin cash) the container vector of blockchain's checkpoints is populated. Litecoin isn't a bitcoin's chain fork so we need to build this vector from zero (file: rules.cpp).

**Comment by patrickdugan** [comment]
Is it strictly necessary?

I guess persistence links to that.

They were able to do a valid client for sending USDT on Litecoin without
having this implemented though?

**Comment by patrickdugan** [comment]
I have a better understanding of this now and believe we did this when we specified the Activation epochs/limited number of activations for our roadmap in rules.cpp?

Therefore we can close this?

**Comment by patrickdugan** [comment]
This was mostly done in Sept. 2021.
